# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Score Board.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 514)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calculate_bt = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_bt.setEnabled(False)
        self.calculate_bt.setGeometry(QtCore.QRect(480, 380, 75, 23))
        self.calculate_bt.setObjectName("calculate_bt")
        self.reset_bt = QtWidgets.QPushButton(self.centralwidget)
        self.reset_bt.setGeometry(QtCore.QRect(260, 410, 75, 23))
        self.reset_bt.setObjectName("reset_bt")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 40, 201, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.p1edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.p1edit.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.p1edit.setText("")
        self.p1edit.setMaxLength(2)
        self.p1edit.setObjectName("p1edit")
        self.p1sc = QtWidgets.QLabel(self.groupBox_3)
        self.p1sc.setGeometry(QtCore.QRect(130, 80, 47, 21))
        self.p1sc.setObjectName("p1sc")
        self.p1result = QtWidgets.QLineEdit(self.groupBox_3)
        self.p1result.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.p1result.setText("")
        self.p1result.setMaxLength(2)
        self.p1result.setObjectName("p1result")
        self.p1sc_2 = QtWidgets.QLabel(self.groupBox_3)
        self.p1sc_2.setGeometry(QtCore.QRect(130, 110, 47, 21))
        self.p1sc_2.setObjectName("p1sc_2")
        self.p1sc_3 = QtWidgets.QLabel(self.groupBox_3)
        self.p1sc_3.setGeometry(QtCore.QRect(130, 50, 47, 21))
        self.p1sc_3.setObjectName("p1sc_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(570, 40, 201, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.p3edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.p3edit.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.p3edit.setMaxLength(2)
        self.p3edit.setObjectName("p3edit")
        self.p3sc = QtWidgets.QLabel(self.groupBox_4)
        self.p3sc.setGeometry(QtCore.QRect(130, 80, 47, 21))
        self.p3sc.setObjectName("p3sc")
        self.p3result = QtWidgets.QLineEdit(self.groupBox_4)
        self.p3result.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.p3result.setText("")
        self.p3result.setMaxLength(2)
        self.p3result.setObjectName("p3result")
        self.p1sc_6 = QtWidgets.QLabel(self.groupBox_4)
        self.p1sc_6.setGeometry(QtCore.QRect(130, 110, 47, 21))
        self.p1sc_6.setObjectName("p1sc_6")
        self.p1sc_7 = QtWidgets.QLabel(self.groupBox_4)
        self.p1sc_7.setGeometry(QtCore.QRect(130, 50, 47, 21))
        self.p1sc_7.setObjectName("p1sc_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 210, 201, 141))
        self.groupBox_6.setObjectName("groupBox_6")
        self.p2edit = QtWidgets.QLineEdit(self.groupBox_6)
        self.p2edit.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.p2edit.setMaxLength(2)
        self.p2edit.setObjectName("p2edit")
        self.p2sc = QtWidgets.QLabel(self.groupBox_6)
        self.p2sc.setGeometry(QtCore.QRect(130, 80, 47, 21))
        self.p2sc.setObjectName("p2sc")
        self.p2result = QtWidgets.QLineEdit(self.groupBox_6)
        self.p2result.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.p2result.setText("")
        self.p2result.setMaxLength(2)
        self.p2result.setObjectName("p2result")
        self.p1sc_4 = QtWidgets.QLabel(self.groupBox_6)
        self.p1sc_4.setGeometry(QtCore.QRect(130, 50, 47, 21))
        self.p1sc_4.setObjectName("p1sc_4")
        self.p1sc_5 = QtWidgets.QLabel(self.groupBox_6)
        self.p1sc_5.setGeometry(QtCore.QRect(130, 110, 47, 21))
        self.p1sc_5.setObjectName("p1sc_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(570, 210, 201, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.p4edit = QtWidgets.QLineEdit(self.groupBox_5)
        self.p4edit.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.p4edit.setMaxLength(2)
        self.p4edit.setObjectName("p4edit")
        self.p4sc = QtWidgets.QLabel(self.groupBox_5)
        self.p4sc.setGeometry(QtCore.QRect(130, 80, 47, 21))
        self.p4sc.setObjectName("p4sc")
        self.p4result = QtWidgets.QLineEdit(self.groupBox_5)
        self.p4result.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.p4result.setText("")
        self.p4result.setMaxLength(2)
        self.p4result.setObjectName("p4result")
        self.p1sc_8 = QtWidgets.QLabel(self.groupBox_5)
        self.p1sc_8.setGeometry(QtCore.QRect(130, 110, 47, 21))
        self.p1sc_8.setObjectName("p1sc_8")
        self.p1sc_9 = QtWidgets.QLabel(self.groupBox_5)
        self.p1sc_9.setGeometry(QtCore.QRect(130, 50, 47, 21))
        self.p1sc_9.setObjectName("p1sc_9")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(350, 210, 101, 141))
        self.groupBox.setObjectName("groupBox")
        self.multi_no = QtWidgets.QRadioButton(self.groupBox)
        self.multi_no.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.multi_no.setChecked(True)
        self.multi_no.setObjectName("multi_no")
        self.multi_yes = QtWidgets.QRadioButton(self.groupBox)
        self.multi_yes.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.multi_yes.setObjectName("multi_yes")
        self.multi = QtWidgets.QComboBox(self.groupBox)
        self.multi.setEnabled(False)
        self.multi.setGeometry(QtCore.QRect(10, 100, 69, 22))
        self.multi.setObjectName("multi")
        self.multi.addItem("")
        self.multi.addItem("")
        self.multi.addItem("")
        self.multi.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 40, 301, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.label_8.setObjectName("label_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(80, 10, 71, 131))
        self.groupBox_7.setObjectName("groupBox_7")
        self.p1call = QtWidgets.QRadioButton(self.groupBox_7)
        self.p1call.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.p1call.setChecked(True)
        self.p1call.setObjectName("p1call")
        self.p2call = QtWidgets.QRadioButton(self.groupBox_7)
        self.p2call.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.p2call.setObjectName("p2call")
        self.p4call = QtWidgets.QRadioButton(self.groupBox_7)
        self.p4call.setGeometry(QtCore.QRect(10, 110, 82, 17))
        self.p4call.setObjectName("p4call")
        self.p3call = QtWidgets.QRadioButton(self.groupBox_7)
        self.p3call.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.p3call.setObjectName("p3call")
        self.risk_gb_yes = QtWidgets.QGroupBox(self.groupBox_2)
        self.risk_gb_yes.setEnabled(False)
        self.risk_gb_yes.setGeometry(QtCore.QRect(160, 10, 71, 131))
        self.risk_gb_yes.setObjectName("risk_gb_yes")
        self.p1risk = QtWidgets.QRadioButton(self.risk_gb_yes)
        self.p1risk.setEnabled(False)
        self.p1risk.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.p1risk.setCheckable(True)
        self.p1risk.setChecked(False)
        self.p1risk.setObjectName("p1risk")
        self.p2risk = QtWidgets.QRadioButton(self.risk_gb_yes)
        self.p2risk.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.p2risk.setObjectName("p2risk")
        self.p4risk = QtWidgets.QRadioButton(self.risk_gb_yes)
        self.p4risk.setGeometry(QtCore.QRect(10, 110, 82, 17))
        self.p4risk.setObjectName("p4risk")
        self.p3risk = QtWidgets.QRadioButton(self.risk_gb_yes)
        self.p3risk.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.p3risk.setObjectName("p3risk")
        self.p1with = QtWidgets.QCheckBox(self.groupBox_2)
        self.p1with.setEnabled(False)
        self.p1with.setGeometry(QtCore.QRect(240, 30, 70, 17))
        self.p1with.setObjectName("p1with")
        self.p2with = QtWidgets.QCheckBox(self.groupBox_2)
        self.p2with.setGeometry(QtCore.QRect(240, 60, 70, 17))
        self.p2with.setObjectName("p2with")
        self.p3with = QtWidgets.QCheckBox(self.groupBox_2)
        self.p3with.setGeometry(QtCore.QRect(240, 90, 70, 17))
        self.p3with.setObjectName("p3with")
        self.p4with = QtWidgets.QCheckBox(self.groupBox_2)
        self.p4with.setGeometry(QtCore.QRect(240, 120, 70, 17))
        self.p4with.setObjectName("p4with")
        self.risk_single_double = QtWidgets.QGroupBox(self.centralwidget)
        self.risk_single_double.setEnabled(False)
        self.risk_single_double.setGeometry(QtCore.QRect(250, 210, 91, 101))
        self.risk_single_double.setObjectName("risk_single_double")
        self.double_risk = QtWidgets.QRadioButton(self.risk_single_double)
        self.double_risk.setGeometry(QtCore.QRect(10, 70, 82, 17))
        self.double_risk.setChecked(False)
        self.double_risk.setObjectName("double_risk")
        self.risk = QtWidgets.QRadioButton(self.risk_single_double)
        self.risk.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.risk.setChecked(True)
        self.risk.setObjectName("risk")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setEnabled(True)
        self.groupBox_10.setGeometry(QtCore.QRect(460, 210, 91, 101))
        self.groupBox_10.setObjectName("groupBox_10")
        self.risk_no = QtWidgets.QRadioButton(self.groupBox_10)
        self.risk_no.setGeometry(QtCore.QRect(10, 70, 82, 17))
        self.risk_no.setChecked(True)
        self.risk_no.setObjectName("risk_no")
        self.risk_yes = QtWidgets.QRadioButton(self.groupBox_10)
        self.risk_yes.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.risk_yes.setObjectName("risk_yes")
        self.clear_bt = QtWidgets.QPushButton(self.centralwidget)
        self.clear_bt.setGeometry(QtCore.QRect(260, 350, 75, 23))
        self.clear_bt.setObjectName("clear_bt")
        self.call1 = QtWidgets.QLabel(self.centralwidget)
        self.call1.setEnabled(True)
        self.call1.setGeometry(QtCore.QRect(50, 60, 31, 16))
        self.call1.setAutoFillBackground(False)
        self.call1.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.call1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.call1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.call1.setScaledContents(False)
        self.call1.setObjectName("call1")
        self.call2 = QtWidgets.QLabel(self.centralwidget)
        self.call2.setEnabled(True)
        self.call2.setGeometry(QtCore.QRect(50, 230, 31, 16))
        self.call2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.call2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.call2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.call2.setObjectName("call2")
        self.call3 = QtWidgets.QLabel(self.centralwidget)
        self.call3.setEnabled(True)
        self.call3.setGeometry(QtCore.QRect(590, 60, 31, 16))
        self.call3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.call3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.call3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.call3.setObjectName("call3")
        self.call4 = QtWidgets.QLabel(self.centralwidget)
        self.call4.setEnabled(True)
        self.call4.setGeometry(QtCore.QRect(590, 230, 31, 16))
        self.call4.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.call4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.call4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.call4.setObjectName("call4")
        self.with1 = QtWidgets.QLabel(self.centralwidget)
        self.with1.setEnabled(True)
        self.with1.setGeometry(QtCore.QRect(110, 60, 31, 16))
        self.with1.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.with1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.with1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.with1.setScaledContents(False)
        self.with1.setObjectName("with1")
        self.with2 = QtWidgets.QLabel(self.centralwidget)
        self.with2.setEnabled(True)
        self.with2.setGeometry(QtCore.QRect(110, 230, 31, 16))
        self.with2.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.with2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.with2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.with2.setObjectName("with2")
        self.with3 = QtWidgets.QLabel(self.centralwidget)
        self.with3.setEnabled(True)
        self.with3.setGeometry(QtCore.QRect(650, 60, 31, 16))
        self.with3.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.with3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.with3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.with3.setObjectName("with3")
        self.with4 = QtWidgets.QLabel(self.centralwidget)
        self.with4.setEnabled(True)
        self.with4.setGeometry(QtCore.QRect(650, 230, 31, 16))
        self.with4.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.with4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.with4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.with4.setObjectName("with4")
        self.risk1 = QtWidgets.QLabel(self.centralwidget)
        self.risk1.setEnabled(True)
        self.risk1.setGeometry(QtCore.QRect(170, 60, 31, 16))
        self.risk1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.risk1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.risk1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.risk1.setScaledContents(False)
        self.risk1.setObjectName("risk1")
        self.risk2 = QtWidgets.QLabel(self.centralwidget)
        self.risk2.setEnabled(True)
        self.risk2.setGeometry(QtCore.QRect(170, 230, 31, 16))
        self.risk2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.risk2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.risk2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.risk2.setObjectName("risk2")
        self.risk4 = QtWidgets.QLabel(self.centralwidget)
        self.risk4.setEnabled(True)
        self.risk4.setGeometry(QtCore.QRect(710, 230, 31, 16))
        self.risk4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.risk4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.risk4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.risk4.setObjectName("risk4")
        self.risk3 = QtWidgets.QLabel(self.centralwidget)
        self.risk3.setEnabled(True)
        self.risk3.setGeometry(QtCore.QRect(710, 60, 31, 16))
        self.risk3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.risk3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.risk3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.risk3.setObjectName("risk3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.p1call.toggled['bool'].connect(self.call1.setVisible)
        self.p2call.toggled['bool'].connect(self.call2.setVisible)
        self.p3call.toggled['bool'].connect(self.call3.setVisible)
        self.p4call.toggled['bool'].connect(self.call4.setVisible)
        self.p1with.toggled['bool'].connect(self.with1.setVisible)
        self.p2with.toggled['bool'].connect(self.with2.setVisible)
        self.p3with.toggled['bool'].connect(self.with3.setVisible)
        self.p4with.toggled['bool'].connect(self.with4.setVisible)
        self.p1risk.toggled['bool'].connect(self.risk1.setVisible)
        self.p2risk.toggled['bool'].connect(self.risk2.setVisible)
        self.p3risk.toggled['bool'].connect(self.risk3.setVisible)
        self.p4risk.toggled['bool'].connect(self.risk4.setVisible)
        self.risk_yes.toggled['bool'].connect(self.risk_gb_yes.setEnabled)
        self.risk_yes.toggled['bool'].connect(self.risk_single_double.setEnabled)
        self.multi_yes.toggled['bool'].connect(self.multi.setEnabled)
        self.p1call.toggled['bool'].connect(self.p1with.setDisabled)
        self.p1call.toggled['bool'].connect(self.p1risk.setDisabled)
        self.p2call.toggled['bool'].connect(self.p2with.setDisabled)
        self.p2call.toggled['bool'].connect(self.p2risk.setDisabled)
        self.p3call.toggled['bool'].connect(self.p3with.setDisabled)
        self.p3call.toggled['bool'].connect(self.p3risk.setDisabled)
        self.p4call.toggled['bool'].connect(self.p4with.setDisabled)
        self.p4call.toggled['bool'].connect(self.p4risk.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Estimation Score Board"))
        self.calculate_bt.setText(_translate("MainWindow", "Calculate"))
        self.reset_bt.setText(_translate("MainWindow", "Reset"))
        self.groupBox_3.setTitle(_translate("MainWindow", "player 1"))
        self.p1sc.setText(_translate("MainWindow", "score"))
        self.p1sc_2.setText(_translate("MainWindow", "Result"))
        self.p1sc_3.setText(_translate("MainWindow", "Call"))
        self.groupBox_4.setTitle(_translate("MainWindow", "player3"))
        self.p3sc.setText(_translate("MainWindow", "score"))
        self.p1sc_6.setText(_translate("MainWindow", "Result"))
        self.p1sc_7.setText(_translate("MainWindow", "Call"))
        self.groupBox_6.setTitle(_translate("MainWindow", "player2"))
        self.p2sc.setText(_translate("MainWindow", "score"))
        self.p1sc_4.setText(_translate("MainWindow", "Call"))
        self.p1sc_5.setText(_translate("MainWindow", "Result"))
        self.groupBox_5.setTitle(_translate("MainWindow", "player4"))
        self.p4sc.setText(_translate("MainWindow", "score"))
        self.p1sc_8.setText(_translate("MainWindow", "Result"))
        self.p1sc_9.setText(_translate("MainWindow", "Call"))
        self.groupBox.setTitle(_translate("MainWindow", "Multiplication"))
        self.multi_no.setText(_translate("MainWindow", "No"))
        self.multi_yes.setText(_translate("MainWindow", "Yes"))
        self.multi.setCurrentText(_translate("MainWindow", "x2"))
        self.multi.setItemText(0, _translate("MainWindow", "x2"))
        self.multi.setItemText(1, _translate("MainWindow", "x4"))
        self.multi.setItemText(2, _translate("MainWindow", "x6"))
        self.multi.setItemText(3, _translate("MainWindow", "x8"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Call / Risk / With"))
        self.label_5.setText(_translate("MainWindow", "player1"))
        self.label_6.setText(_translate("MainWindow", "player2"))
        self.label_7.setText(_translate("MainWindow", "player3"))
        self.label_8.setText(_translate("MainWindow", "player4"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Call"))
        self.p1call.setText(_translate("MainWindow", "Call"))
        self.p2call.setText(_translate("MainWindow", "Call"))
        self.p4call.setText(_translate("MainWindow", "Call"))
        self.p3call.setText(_translate("MainWindow", "Call"))
        self.risk_gb_yes.setTitle(_translate("MainWindow", "Risk"))
        self.p1risk.setText(_translate("MainWindow", "Yes"))
        self.p2risk.setText(_translate("MainWindow", "Yes"))
        self.p4risk.setText(_translate("MainWindow", "Yes"))
        self.p3risk.setText(_translate("MainWindow", "Yes"))
        self.p1with.setText(_translate("MainWindow", "With"))
        self.p2with.setText(_translate("MainWindow", "With"))
        self.p3with.setText(_translate("MainWindow", "With"))
        self.p4with.setText(_translate("MainWindow", "With"))
        self.risk_single_double.setTitle(_translate("MainWindow", "Risk"))
        self.double_risk.setText(_translate("MainWindow", "Double Risk"))
        self.risk.setText(_translate("MainWindow", "Risk"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Risk"))
        self.risk_no.setText(_translate("MainWindow", "No"))
        self.risk_yes.setText(_translate("MainWindow", "Yes"))
        self.clear_bt.setText(_translate("MainWindow", "Clear"))
        self.call1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Call</span></p></body></html>"))
        self.call2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Call</span></p></body></html>"))
        self.call3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Call</span></p></body></html>"))
        self.call4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Call</span></p></body></html>"))
        self.with1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ffffff;\">With</span></p></body></html>"))
        self.with2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ffffff;\">With</span></p></body></html>"))
        self.with3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ffffff;\">With</span></p></body></html>"))
        self.with4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ffffff;\">With</span></p></body></html>"))
        self.risk1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ff0000;\">Risk</span></p></body></html>"))
        self.risk2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ff0000;\">Risk</span></p></body></html>"))
        self.risk4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ff0000;\">Risk</span></p></body></html>"))
        self.risk3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; font-weight:600; color:#ff0000;\">Risk</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

